config/routes.rb
Mongo::Application.routes.draw do
  resources :reviews

  resources :products

  resources :messages

  resources :dialogs do
    get :enter, on: :collection
    get :done, on: :collection
    get :exit, on: :collection
    get :insert, on: :collection
  end

  devise_for :users
  resources :users

  resources :pages do
    get :hui
  end

  resources :areas

  root 'pages#hui'
  get 'sitemap' => 'areas#sitemap'
  get ':id' => 'areas#show'
  get ':id/:page' => 'areas#show'
  post 'e/inc/xxxqwer' => 'incoming#event'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :admin_filter
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:author, :text)
    end

    def admin_filter
      render text: 'fucking hacker' unless current_user.try(:admin)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= form_for @review do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit 'Save'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Listing reviews

%table.table.table-bordered.table-condensed
  %tr
    %th Author
    %th Text
    %th
    %th
    %th

  - @reviews.each do |review|
    %tr
      %td= review.author
      %td= review.text
      %td= link_to 'Show', review
      %td= link_to 'Edit', edit_review_path(review)
      %td= link_to 'Destroy', review, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

= link_to 'Back', reviews_path

app/views/reviews/show.html.haml
%p#notice= notice

%p
  %b Author:
  = @review.author
%p
  %b Text:
  = @review.text

= link_to 'Edit', edit_review_path(@review)
\|
= link_to 'Back', reviews_path