config/routes.rb
Mongo::Application.routes.draw do
  resources :reviews

  resources :products

  resources :messages

  resources :dialogs do
    get :enter, on: :collection
    get :done, on: :collection
    get :exit, on: :collection
    get :insert, on: :collection
  end

  devise_for :users
  resources :users

  resources :pages do
    get :hui
  end

  resources :areas

  root 'pages#hui'
  get 'sitemap' => 'areas#sitemap'
  get ':id' => 'areas#show'
  get ':id/:page' => 'areas#show'
  post 'e/inc/xxxqwer' => 'incoming#event'

end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-9", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Навигация
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "#"} KupiLegal
    #bs-example-navbar-collapse-9.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{href: "#"} Работай с нами
        %li
          %a{href: "#"} Заказывай почтой
        %li
          %a{href: "#"} Каталог
        %li
          %a{href: "#"} Отзывы
        - if current_user.try(:admin)
          %li= link_to ('Диалоги ' + Dialog.count.to_s ), dialogs_path
          %li= link_to ('Сообщения ' + Message.count.to_s), messages_path
          %li= link_to ('Отзывы ' + Review.count.to_s), reviews_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    - if @page.present? && @area.present?
      %title= @page.title.to_s + ' ' + @area.title
    - else
      %title= "Купить спайс, соль, курительные смеси" + ((' - ' + @area.title.to_s ) if @area.present?).to_s
    %meta{content: 'Закладки, Легал, Купить спайс, Соль для ванн, Курительные смеси', name: "Keywords"}
    %meta{content: 'Проверенный магазин, отзывы клиентов, купи открытку и оставь свой отзыв следующим', name: "Description"}
    %meta{name: "google-site-verification", content: "MhLyNTyOFdTfX9SXLhP350q8Q91v6NkWOetOkujYqiU"}
    %meta{name: 'yandex-verification', content: '7c991dd0c36c87ca'}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :js
    = javascript_include_tag 'jquery.ui.touch-punch.min'
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    .container
      #notice= notice
      = yield

    -#%small
    -#  - @pages.each do |p|
    -#    %a{href: ('http://kupilegal.ru/' + @area.slug + '/' + p.slug)}= p.title + ' ' + @area.title
    - unless Rails.env.development?
      - unless current_user.try(:admin)
        = render 'templates/ya'
        = render 'templates/ga'

-#42b027d2001e4bb24cf5@cloudmailin.net